### ISSUE TITLE
Active Window Hint Not Selectable

### ISSUE THREAD

**Issue by drewofdoom** [carlwgeorge/gnome-shell-extension-pop-shell#1]
Selecting the active window hint color is a new feature in pop-shell, but doesn't appear to work properly here. Clicking the item in the drop-down just silently fails.

Steps to reproduce:
Click on the extension button (usually in the top bar next to system drop-down)
Click on "Active Hint Color"

A color selector should appear, but nothing happens.

**Comment by carlwgeorge** [comment]
Thanks for noticing this.  I'm not using the upstream Makefile's compile target directly, because I want to let glib2's file triggers handle the schema compilation.  They [added a new file](https://github.com/pop-os/shell/commit/cc00d2fe47bfe2ac128c35a18d649c8899aa12ef) that I had to adjust my copy command to account for.
